### PR TITLE
t/ckeditor5/810: Made the link form buttons thicker with a fill color and no background.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Made the link form buttons thicker with a fill color and no background (see ckeditor/ckeditor5#810).

---

Requires:

1. https://github.com/ckeditor/ckeditor5-core/pull/125
2. https://github.com/ckeditor/ckeditor5-theme-lark/pull/161

### CODE REVIEW

**Comment by oleq** [comment]
Retina

screen shot 2018-03-15 at 12 14 02


Non-retina

screen shot 2018-03-15 at 12 15 18

**Comment by scofalik** [comment]
Just a small thing but could we put those icons a bit closer to each other? So the gap between them is same as gaps between field and icon, or icon and tooltip border.

**Comment by oleq** [comment]
@scofalik We cannot because it's a framework not a patchwork :P

image

**Comment by scofalik** [comment]
Yeah that's what I thought. Bummer.

**Comment by oleq** [comment]
I found out I slightly exaggerated the thickness. I updated the icons:

Retina
screen shot 2018-03-15 at 12 31 55

Non-retina
screen shot 2018-03-15 at 12 34 19

**Pull request merged**
