### PR TITLE
Changed the way of checking of linkCommand is enabled.

### LINKED ISSUE #39: UnlinkCommand#hasValue should be solved by #isEnabled
That's exactly what for `isEnabled` is defined in the `Command` class.

### PR DESCRIPTION
**Pull request by oskarwrobel**
Fixes #39

### CODE REVIEW

**Comment by Reinmar** [comment]
1 failing test in http://tests.ckeditor.dev:1030/build/modules/amd/tests/link/link.

**Comment by oskarwrobel** [comment]
Which one?
I have all green.

image

**Comment by Reinmar** [comment]
http://tests.ckeditor.dev:1030/build/modules/amd/tests/link/link#unlink%20toolbar%20button%20should%20bind%20unlinkButton%23model%20to%20unlink%20command

Did you pull the branch? I merged master into it.

**Comment by oskarwrobel** [comment]
OK, it should fail even before merged master. I have one uncommitted local change.

**Comment by oskarwrobel** [comment]
Should work now.

**Pull request merged**
