### PR TITLE
t/52: Removed the "Unlink" button from the toolbars

### LINKED ISSUE #52: Remove the "unlink" button from the toolbar
The unlinking feature is already available in the link editing ballon. This is great, because we can have one less button in the toolbar. The less, the better.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Removed the "Unlink" button from the toolbars. Closes #52.

---

### Additional information

Branches in other repositories:
* https://github.com/ckeditor/ckeditor5-block-quote/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-editor-inline/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-presets/tree/t/ckeditor5-link/52
* https://github.com/ckeditor/ckeditor5-ui/tree/t/ckeditor5-link/52

### CODE REVIEW

**Comment by Reinmar** [comment]
We were supposed to also remove the UI component for it.

**Comment by oleq** [comment]
Why exactly? People may want to use it after all.

**Comment by Reinmar** [comment]
Because, as [disscussed](https://github.com/ckeditor/ckeditor5-link/issues/52#issuecomment-252865727), if we keep it in the code we need to maintain it. And if we don't use it, then it doesn't make much sense.

Plus, to keep the code size as low as possible, this should be a separate feature. That will avoid loading its icon.

**Comment by oleq** [comment]
OK, I removed the UI component. I also found out that I missed changes in the build-classic package so I updated it too.

The CI branch is https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-link/52.

**Comment by Reinmar** [comment]
You somehow missed all the docs:

image

**Comment by Reinmar** [comment]
I'll handle them while closing this PR.

**Comment by oleq** [comment]
The mystery why I missed them is `folder_exclude_patterns` in the ST project configuration :P

**Comment by Reinmar** [comment]
I thought so :D

**Pull request merged**
