### PR TITLE
Improved focus managing before removing the active element from the DOM

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Improved focus managing before removing the active element from the DOM. Closes https://github.com/ckeditor/ckeditor5/issues/1501.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by oleq** [comment]
LGTM but... why does this issue never happens with the image text alternative balloon/input? It's pretty much the same thing.

**Comment by oskarwrobel** [comment]
I think we have similar issues with image. We can check and fix all of them while working on https://github.com/ckeditor/ckeditor5-ui/issues/468.

**Comment by oleq** [comment]
This PR does not fix #193

**Comment by oskarwrobel** [comment]
You are right. It fixes only some paths (not all).

**Pull request merged**
