### PR TITLE
Fixed `Schema#allow()` entry.

### LINKED ISSUE #97: Schema is set incorrectly.
`Schema#allow()` entry should have `inside` part set up, otherwise the element is allowed everywhere. See https://github.com/ckeditor/ckeditor5-engine/issues/532#issuecomment-292892032

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Schema is now correctly set for Link feature. Closes #97.

### CODE REVIEW

**Comment by Reinmar** [comment]
Misses a test for the thing which was actually supposed to be fixed.

**Comment by Reinmar** [comment]
Two tests could be written – what happens with links which are being inserted directly into the root and a simple schema check whether link is allowed directly in a root.

**Comment by scofalik** [comment]
> Misses a test for the thing which was actually supposed to be fixed.

What was actually supposed to be fixed is that `<a>` wasn't autoparagraphed, but this is an integration test which will fail anyway because of another issue in link. We expect `<paragraph><$text linkHref="url">foo</$text></paragraph>` but after this is fixed we will get `<paragraph>foo</paragraph>`. Is there any use in writing incorrect test?

> Two tests could be written – what happens with links which are being inserted directly into the root

* If I add it through `editor.setData()` I won't get any link (ATM).
* If I will try to add it through model setting util I will get error that schema does not allow text in root
* If I will add it through `doc.batch()` it will be inserted and converted but this is adding something against schema rules so that test is incorrect anyway.

> and a simple schema check whether link is allowed directly in a root.

I'll add this one but I don't tests like this (as there are infinite examples where text with link is not allowed).

**Comment by scofalik** [comment]
Okay you know what, I'll write that integration test. It will fail after the issue in paragraph is fixed and then we will fix that test so we won't forget about that case.

**Comment by Reinmar** [comment]
> We expect <paragraph><$text linkHref="url">foo</$text></paragraph> but after this is fixed we will get <paragraph>foo</paragraph>. Is there any use in writing incorrect test?

IMO, there's a lot of sense in writing such tests. We will have to change that incorrect test once paragraph is fixed. You will know very well that something has changed because it will start failing.  For now, the test will just confirm how it currently behaves and that there are no other issues (e.g. it does not crash).

**Comment by Reinmar** [comment]
> Okay you know what, I'll write that integration test. It will fail after the issue in paragraph is fixed and then we will fix that test so we won't forget about that case.

:D I've read it after writing my previous comment. So, yep – that's the idea.

**Pull request merged**
